version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/Xnopyt/discord-bot-tui

    steps:
      - checkout
      - run: go get -u github.com/Xnopyt/discord-bot-tui/...
      - run:
          name: run build
          command: |
            go build -v
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...